### ISSUE TITLE
Is there a quick way to let utop know the working directory of a source file in emacs?

### ISSUE THREAD

**Issue by xin-jin** [diml/utop#123]
Hi, say, if I open a source file in a random directory in emacs, and I want to eval the buffer in utop. Is there a way to quickly add that random directory to the PATH of utop? I tried something like `utop -emacs -I default-directory` but it does not work.

The specific situation is: my code will input data from a file (both the code and the input file in the same directory), and I want utop to be able to find that input file when I evaluate my code in utop.

Thanks!

**Comment by diml** [comment]
The process should be run in the same directory of the file being visited, so `-I .` should do. Also note that you can use `utop-eval-buffer` to send all of the current buffer to utop.

**Comment by xin-jin** [comment]
Ah, thanks. It works!

**Comment by chetnashah** [comment]
I am sending a buffer using M-x utop-eval-buffer,
But it gives error : 
```
utop-compat-skip-blank-and-comments: Symbol's function definition is void: tuareg-skip-blank-and-comments
```
Is there something I am missing?

**Comment by chetnashah** [comment]
I think utop-eval-buffer is broken probably because of recent commit in tuareg by renaming of 
tuareg-skip-blank-and-comments to tuareg--skip-blank-and-comments (two-dashes)
