### ISSUE TITLE
Error when compiling utop.1.14  using 4.02.1 compiler

### ISSUE THREAD

**Issue by michalskuza** [diml/utop#125]
The following actions will be performed:
     - install   utop.1.14
    === 1 to install ===    

    =-=- Synchronizing package archives -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=    

    =-=- Installing packages =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
    Building utop.1.14:
      ocaml setup.ml -configure --prefix /Users/michal/.opam/system
      ocaml setup.ml -build
      ocaml setup.ml -install
    [ERROR] The compilation of utop.1.14 failed.
    Removing utop.1.14.
      ocamlfind remove utop    
    

    #=== ERROR while installing utop.1.14 =========================================#
    # opam-version 1.2.0
    # os           darwin
    # command      ocaml setup.ml -build
    # path         /Users/michal/.opam/system/build/utop.1.14
    # compiler     system (4.02.1)
    # exit-code    1
    # env-file     /Users/michal/.opam/system/build/utop.1.14/utop-7188-c61e7b.env
    # stdout-file  /Users/michal/.opam/system/build/utop.1.14/utop-7188-c61e7b.out
    # stderr-file  /Users/michal/.opam/system/build/utop.1.14/utop-7188-c61e7b.err
    ### stdout ###
    # ...[truncated]
    # Ill_formed_ast (_, _)
    # /Users/michal/.opam/system/bin/ocamlfind ocamlc -c -g -package findlib -package lambda-term -syntax camlp4o -package lwt.syntax -package threads -syntax camlp4o -thread -ppopt syntax/pa_optcomp.cmo -ppopt -let -ppopt 'findlib_version=(1, 5)' -I /usr/local/lib/ocaml/compiler-libs -I src/lib -o src/lib/uTop_main.cmo src/lib/uTop_main.ml
    # + /Users/michal/.opam/system/bin/ocamlfind ocamlc -c -g -package findlib -package lambda-term -syntax camlp4o -package lwt.syntax -package threads -syntax camlp4o -thread -ppopt syntax/pa_optcomp.cmo -ppopt -let -ppopt 'findlib_version=(1, 5)' -I /usr/local/lib/ocaml/compiler-libs -I src/lib -o src/lib/uTop_main.cmo src/lib/uTop_main.ml
    # findlib: [WARNING] Interface errors.cmi occurs in several directories: src/lib, /usr/local/lib/ocaml/compiler-libs
    # findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml/compiler-libs, /usr/local/lib/ocaml
    # File "src/lib/uTop_main.ml", line 96, characters 41-45:
    # Error: This expression has type tool_name:string -> Parsetree.structure
    #        but an expression was expected of type
    #          Parsetree.structure = Parsetree.structure_item list
    # Command exited with code 2.
    ### stderr ###
    # ...[truncated]
    # Use Lazy.from_fun instead.
    # I: Searching for OCaml compiler libraries
    # I: Searching for OCaml compiler libraries
    # File "setup.ml", line 254, characters 8-26:
    # Warning 3: deprecated: String.set
    # Use Bytes.set instead.
    # File "setup.ml", line 2509, characters 6-24:
    # Warning 3: deprecated: Lazy.lazy_from_fun
    # Use Lazy.from_fun instead.
    # E: Failure("Command ''/usr/local/bin/ocamlbuild' syntax/optcomp.cma src/lib/utop.cma src/lib/utop.cmxa src/lib/utop.a src/lib/utop.cmxs src/camlp4/utop-camlp4.cma src/camlp4/utop-camlp4.cmxa src/camlp4/utop-camlp4.a src/camlp4/utop-camlp4.cmxs src/top/uTop_top.byte src/top/uTop_top_full.byte -tag debug' terminated with error code 10")

**Comment by whitequark** [comment]
Try 1.17.

**Comment by michalskuza** [comment]
I'm using brew on OS X. How can I choose a particular version of utop ?

**Comment by whitequark** [comment]
`opam install utop.1.17`

**Comment by michalskuza** [comment]
I got this error

    [ERROR] No package matches utop.1.17.

**Comment by whitequark** [comment]
`opam update`

**Comment by michalskuza** [comment]
it works now. This issue can be closed.
