### ISSUE TITLE
string type printed as CamlinternalFormatBasics.char_set

### ISSUE THREAD

**Issue by dsheets** [diml/utop#126]
```ocaml
# #show_module Hex;;
module Hex :
sig
    val of_char : char -> char * char                                               
    val to_char : char -> char -> char
    type t = [ `Hex of CamlinternalFormatBasics.char_set ]
    val of_string : ?pretty:bool -> CamlinternalFormatBasics.char_set -> t
    val to_string : t -> CamlinternalFormatBasics.char_set
  end
```

with utop 1.17

**Comment by dsheets** [comment]
OCaml 4.02.1

**Comment by diml** [comment]
Can you retry with `utop -no-short-paths`?

**Comment by dsheets** [comment]
That works as expected.

**Comment by diml** [comment]
utop enables `-short-paths` by default. It's weird that the typer choose `CamlinterformatBasics.char_set` instead of `string`. Do you get the same behavior with `ocaml -short-paths`? If yes you should report it on the OCaml mantis.

**Comment by dsheets** [comment]
Yes, it's an OCaml bug.

Thanks!

**Comment by dsheets** [comment]
<http://caml.inria.fr/mantis/view.php?id=6763>
