### ISSUE TITLE
Z.mod;; Error: Syntax error

### ISSUE THREAD

**Issue by UnixJunkie** [diml/utop#128]
To reproduce:
require "zarith";;
Z.mod;;

It's strange: Z.add;; just works.

**Comment by UnixJunkie** [comment]
By the way, it gives the same output in a vanila ocaml toplevel ?!

**Comment by whitequark** [comment]
mod is a keyword.

**Comment by UnixJunkie** [comment]
Sorry, I was mistaken by the auto completion of utop.
There is no mod operation in zarith (I was told it's called rem instead).
