### ISSUE TITLE
[Emacs] lwt.ppx issues

### ISSUE THREAD

**Issue by xificurC** [diml/utop#130]
Hi, not sure if I'm doing this wrong or there is some sort of a bug, so bear with me.

The `lwt.ppx` syntax extension doesn't work properly for me in utop running under emacs. [Here](https://github.com/xificurC/theaigames-starter-bot/tree/f0a07d302989ff81a9f1f2873f2f5dfbc39eca88) is the code I'm working with. When I open `main.ml` and `C-c C-s` from there I get utop running with all the libs loaded. Loading each expression in, 1-by-1, with `C-c C-e` works fine but running `C-c C-b` gives me an error on line 22 on the ppx syntax extension, namely it says `Uninterpreted extension 'lwt'`, even though loading it with `C-c C-e` works fine.

I'm on Arch Linux running on utop 1.17, ocaml 4.02.1, emacs 24.4.1 and I fetched the latest `utop.el` and put it in `~/.opam/4.02.1/share/emacs/site-lisp/` to have `utop-minor-mode` working.

Any help/tips appreciated. Cheers

**Comment by rgrinberg** [comment]
I just tried reproducing and it's no longer an issue. @diml you can close this.
