### ISSUE TITLE
A way to use anything but double semicolons.

### ISSUE THREAD

**Issue by jordwalke** [diml/utop#131]
Is there a way to use anything other than double semicolons to tell the top level to try to parse a top level phrase? It would be great if you could configure `<control+cr>` or `<shift+cr>`.

**Comment by whitequark** [comment]
No. This is not really a part of utop but of OCaml's grammar. (You can also use `;;` in source files.)

**Comment by jordwalke** [comment]
@whitequark: I'm aware of `toplevel_phrase`. I also looked at how `m17n` customized `utop` with a custom parser/lexer. I know I can create a custom parser/lexer, but I'm wondering if there's any other hacks I can do in `.lambdaterm.conf` such as triggering the insertion of two semis (and a return). Otherwise, I suppose I'll just have to create a custom parser.

**Comment by whitequark** [comment]
Oh. The sequences in your bugreport did not initially render. (I have fixed them.)

**Comment by jordwalke** [comment]
Okay. Then do you suppose it might be possible via configuring lambdaterm?

**Comment by whitequark** [comment]
Definitely, look at https://github.com/diml/lambda-term/blob/master/lambda-term-inputrc#L32.

**Comment by diml** [comment]
Yeah you could have this in your ~/.lambda-termrc:

```
[read-line]
C-enter: goto-eot, insert(;), insert(;), accept
```

However there seems to be a rendering bug in lambda-term.

Another solution, if you want it even when you just press enter is to add this to your `~/.ocamlinit`:

```ocaml
let orig_parse = !UTop.parse_toplevel_phrase in
UTop.parse_toplevel_phrase := (fun str eos_is_error -> orig_parse (str ^ ";;") eos_is_error);;
```

This solution might be better as what will be added to the history is exactly what you typed. Note that if you are using camlp4 you need to run this after `#camlp4o`.

**Comment by hcarty** [comment]
A quick and dirty function you could add to `.ocamlinit` to toggle between requiring semicolons (ex. for pasting a block of code) and not (for simpler interactive use):
```ocaml
let toggle_semi =
  let original = !UTop.parse_toplevel_phrase in
  let no_semi str eos_is_error = original (str ^ ";;") eos_is_error in
  let semi = ref true in
  fun () ->
    UTop.parse_toplevel_phrase := if !semi then no_semi else original;
    semi := not !semi
```

**Comment by jordwalke** [comment]
Cool, good suggestions.

**Comment by jordwalke** [comment]
I think one issue that I see with some of these suggestions that automatically submit upon hitting `<Enter>`, is that there doesn't seem to be a way to *not* submit on `<Shift+Enter>`, which is how must `REPL`s work (enter submits, shift+enter does multiline input).

**Comment by diml** [comment]
@jordwalke, with 92fafe1f48112742cb496b0ebc60f2a9d5a2df8c you can do both: you can bind enter to automatically add `;;` and something else to always insert a newline. In fact `<Meta+Enter>` is already bound to insert a newline. It is not `<Shift+Enter>` as this combination is not available in the terminal (you can't distinguish it from just `<Enter>`).

**Comment by jordwalke** [comment]
@diml  Thanks for reminding me. With your gist on `utop1.18`:


    #require "lambda-term";;
    LTerm_read_line.bind
      [ { control = false; meta = false; shift = false; code = Enter } ]
      [ UTop.end_and_accept_current_phrase ]


...it seems that hitting enter during a `<c-r>` history search seems to fail with the error:

    Fatal error: exception File "src/lib/uTop.cppo.ml", line 81, characters 26-32: Assertion failed

If I had to guesse, I'd say the intended behavior is for `end_and_accept_current_phrase` to *not* complete the selected history, and instead append the `;;` to whatever they have manually typed, but instead, it just fatals.

(Btw, off topic but I really appreciate the ability to set the custom separator with `set_phrase_terminator`).

**Comment by jordwalke** [comment]
I also notice that with your suggested keybinding above, the following fatals `utop`:

      let x = List.map (fun x -> x) [<Enter>

Instead of fataling `utop`, it should probably gracefully show a parsing error of some kind.

**Comment by diml** [comment]
@jordwalke I fixed the first failure but I can't reproduce the second one
