### ISSUE TITLE
utop crashes with any key hit !

### ISSUE THREAD

**Issue by arthwang** [diml/utop#132]
My utop on centos 7 crashed every time when i strike any key with the infomation:
Fatal error: exception File "src/react.ml", line 411, characters 54-60: Assertion failed

How can i fix it?

Thank you!

**Comment by arthwang** [comment]
I've fixed it by reinstalling relative packages.

**Comment by dsheets** [comment]
I see this with React 0.9.4, 1.1.0, and 1.2.0 with utop 1.15 and 1.2.1.

**Comment by dsheets** [comment]
Sorry, I forgot to mention this only occurs for me on OCaml 4.00.1.
