### ISSUE TITLE
Utop not waiting for Deferred to determine then displaying result

### ISSUE THREAD

**Issue by genkimarshall** [diml/utop#137]
It is my understanding, as per [here](https://realworldocaml.org/v1/en/html/concurrent-programming-with-async.html), that `utop` understands Deferreds and has a scheduler going on to evaluate given Deferred values and display the result.

However, the current behavior for me is:
```OCaml
# let one = return 1;;
val one : int Deferred.t = <abstr>
# one;;
- : int Deferred.t = <abstr>
```
Whereas I believe that last line should display `- : int = 1`.

For reference, my `.ocamlinit` is:
```OCaml
#use "topfind"
#thread
#camlp4o
#require "core.syntax"
#require "core.top"
open Core.Std
#require "async"
open Async.Std
```

OCaml version 4.02.3, async version 112.35.00, utop version 1.18, Linux x64.

Please let me know if I'm missing/misunderstanding something. Thanks in advance for your time.

**Comment by agarwal** [comment]
I'm also getting this incorrect behavior just now with utop 1.18 (and OCaml 4.02.1). The problem doesn't occur with utop 1.17. This is weird because I didn't update utop recently and haven't had this problem before. I use async in utop all the time, so I'm unsure what changed.

**Comment by diml** [comment]
It's due to an update in Async. `Deferred.t` as many aliases so utop follow them all and match on the real definition. It recently moved from `Async_kernel.Ivar.Deferred.t` to `Async_kernel.Deferred0.t`.

**Comment by genkimarshall** [comment]
Great, thank you!

**Comment by siburu** [comment]
This seems not to work now since Async changed again, to Deferred1 ? 

[On El Capitan]
utop # Async.Std.return 1;;
- : int Async_kernel.Deferred1.t = <abstr>

**Comment by diml** [comment]
I pushed a better fix: instead of hard-coding a list of aliases, I resolve the type `Async.Std.Deferred.t`. This will be more future-proof

**Comment by siburu** [comment]
Thank you very much.
I built the latest version and it works fine.

**Comment by siburu** [comment]
Execuse me.
I found that this issue has been already fixed by the commit 2a8762c0f in Aug, 2015.

However, the fix seems not to be reflected to utop 1.18.1.
1.18 and 1.18.1 look identical except for some meta data.
I downloaded v1.18 and v1.18.1 from https://opam.ocaml.org/packages/utop/ and compared them:
```
bash-3.2$ diff -r utop-1.18* | grep ^diff 
diff -r utop-1.18/_oasis utop-1.18.1/_oasis
diff -r utop-1.18/setup.ml utop-1.18.1/setup.ml
diff -r utop-1.18/src/lib/META utop-1.18.1/src/lib/META
diff -r utop-1.18/src/lib/uTop.cppo.ml utop-1.18.1/src/lib/uTop.cppo.ml
```

I'm sorry in advance if my thought is wrong.

**Comment by diml** [comment]
utop-1.18.1 was just a release to fix an incompatibility with the last version of findlib. I need to sort out a few things before the next release but I haven't found the time to do it recently

**Comment by siburu** [comment]
OK, I have understood the situation.
I didn't mean to rush you.
And thank you again for your quick response!

**Comment by Vintila** [comment]
Same issue with utop-1.18.2, async 113.24.00
