### ISSUE TITLE
problems using lacaml from utop

### ISSUE THREAD

**Issue by nilsbecker** [diml/utop#141]
this is a bit similar to #21 but not the same i think. 

    eval `opam config env`
    utop
    #require lacaml;;
    open Lacaml.D;;
    let mat = Mat.random 23 43;;
    > Error: Reference to undefined global `Lacaml'

this works just fine when i replace `utop` with `ocaml` and `#use "topfind"` !?

everything was installed with opam.

**Comment by diml** [comment]
Can you type `#topfind_verbose true;;` at the beginning of the utop session, and then copy-paste the output of `#require lacaml;;`?

**Comment by nilsbecker** [comment]
ok: 

    /Users/<>/.opam/4.02.3/lib/bytes: added to search path                                
    /Users/<>/.opam/4.02.3/lib/lacaml: added to search path

where `<>` is my user name

**Comment by nilsbecker** [comment]
for comparison, when i do it from ocaml toplevel, i get

    #require "lacaml";;
    /Users/<>/.opam/4.02.3/lib/ocaml/unix.cma: loaded
    /Users/<>/.opam/4.02.3/lib/ocaml/bigarray.cma: loaded
    /Users/<>/.opam/4.02.3/lib/bytes: added to search path
    /Users/<>/.opam/4.02.3/lib/lacaml: added to search path
    /Users/<>/.opam/4.02.3/lib/lacaml/lacaml.cma: loaded
    /Users/<>/.opam/4.02.3/lib/lacaml/lacaml_top.cma: loaded

**Comment by diml** [comment]
Do you have an ~/.ocamlinit file?

**Comment by nilsbecker** [comment]
yes: 

    (* Added by OPAM. *)
    let () =
      try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
      with Not_found -> ()
    ;;

**Comment by diml** [comment]
And this is the utop installed by opam, not a custom built one? Can you also paste the contents of the lacaml's META file?

**Comment by nilsbecker** [comment]
utop should be from opam, i just tried `opam reinstall utop` which yields the same result. the meta file in the build dir is 


    # OASIS_START
    # DO NOT EDIT (digest: 0698ad173b56af2141308c74f64db538)
    version = "7.2.6"
    description = "OCaml-bindings to BLAS and LAPACK."
    requires = "bigarray bytes"
    archive(byte) = "lacaml.cma"
    archive(byte, plugin) = "lacaml.cma"
    archive(native) = "lacaml.cmxa"
    archive(native, plugin) = "lacaml.cmxs"
    exists_if = "lacaml.cma"
    package "top" (
     version = "7.2.6"
     description = "Toplevel module for Lacaml."
     requires = "lacaml"
     archive(byte) = "lacaml_top.cma"
     archive(byte, plugin) = "lacaml_top.cma"
     archive(native) = "lacaml_top.cmxa"
     archive(native, plugin) = "lacaml_top.cmxs"
     exists_if = "lacaml_top.cma"
    )
    # OASIS_STOP
    
    #requires(toploop) += "lacaml.top"
    archive(toploop,byte) += "lacaml_top.cma"
    archive(toploop,native) += "lacaml_top.cmxa"

**Comment by nilsbecker** [comment]
`type utop` says that it's the one from my current opam switch

**Comment by diml** [comment]
Ah, it seems to be a problem with the latest findlib. I upgraded my opam and now it doesn't work anymore. For some reason the list of finlib predicates seems to have dropped down: 

```ocaml
# Topfind.predicates;;
- : bytes list ref = {contents = ["pkg_utop"; "toploop"]}
``

I'll investigate

**Comment by diml** [comment]
OK, I pushed something. Could you try and confirm that it works for you?

/ccing @gerdstolpmann, in case this was an unwanted change in findlib. In findlib 1.5.6 custom toplevels have much less predicates by default:

```ocaml
$ echo 'Topfind.load ["findlib"]' > top.ml
$ ocamlfind ocamlmktop -o top -predicates foo -linkpkg -package findlib top.ml
$ ./top -init /dev/null
/home/jdimino/code/opam-root/4.02.3/lib/findlib: added to search path
        OCaml version 4.02.3

# Topfind.predicates;;
- : string list ref = {contents = ["toploop"]}
```

(I looked in the ChangeLog but there was nothing about it)

**Comment by nilsbecker** [comment]
yes! the example succeeds when utop is opam pinned to --dev-repo and reinstalled!

**Comment by diml** [comment]
Ok, I'll do a release soon

**Comment by diml** [comment]
Released in opam
