### ISSUE TITLE
#pwd directive?

### ISSUE THREAD

**Issue by nilsbecker** [diml/utop#149]
seems like it would be useful?

**Comment by diml** [comment]
Sure, why not

**Comment by nilsbecker** [comment]
cool, thanks. just as a suggestion: `%quickref` in ipython has a list of their directives. many are of course not applicable, but e.g. 'mv' 'cp' 'rm' 'ls' 'mkdir' may be interesting? also, they have a handy 'time' and 'timeit' directive for timing evaluation, which may be of interest...

**Comment by diml** [comment]
One problem is that directives are limited in what they can take as argument, from `toploop.mli`:

```ocaml
type directive_fun =
   | Directive_none of (unit -> unit)
   | Directive_string of (string -> unit)
   | Directive_int of (int -> unit)
   | Directive_ident of (Longident.t -> unit)
   | Directive_bool of (bool -> unit)
```

You can't get things like `#cp` with this API so ocaml directives would need to be extended first.

**Comment by nilsbecker** [comment]
i see (sorry for the late reply, just came across this again). for the time being one could maybe have `#!` of type `Directive_string` to shell out?
