### ISSUE TITLE
utop-setup-ocaml-buffer' is deprecated, you need to replace it by utop-minor-mode

### ISSUE THREAD

**Issue by nscott32** [diml/utop#153]
Hello,
I alays have error "utop-setup-ocaml-buffer' is deprecated, you need to replace it by utop-minor-mode" when launching tuareg mode, what is annoying is that I can't run a service daemon with scratch buffer set to tuareg since the error makes the service fails.
How can I fix this ?

**Comment by diml** [comment]
Do you have `utop-setup-ocaml-buffer` in your ~/.emacs? Have you tried replacing it with `utop-minor-mode`?

**Comment by diml** [comment]
(The emacs utop mode is part of utop, so I think this is the right place to ask)

**Comment by nscott32** [comment]
They are in utop.el :
 (defun utop-setup-ocaml-buffer ()
  "Deprecated"
  (error "`utop-setup-ocaml-buffer' is deprecated, you need to
replace it by `utop-minor-mode'.

See https://github.com/diml/utop for configuration information."))

;;;###autoload
(define-minor-mode utop-minor-mode
  "Minor mode for utop."
  :lighter " utop"
  :keymap (let ((map (make-sparse-keymap)))
            (define-key map (kbd "C-c C-s") 'utop)
            (define-key map (kbd "C-x C-e") 'utop-eval-phrase)
            (define-key map (kbd "C-x C-r") 'utop-eval-region)
            (define-key map (kbd "C-c C-b") 'utop-eval-buffer)
            (define-key map (kbd "C-c C-k") 'utop-kill)
            map)
  ;; Load local file variables
  (add-hook 'hack-local-variables-hook 'utop-hack-local-variables))

**Comment by nscott32** [comment]
How would I replace it ?

**Comment by diml** [comment]
You get the error when the function is called, so it must be called from your ~/.emacs

**Comment by nscott32** [comment]
It's called by the code (tuareg-mode).
I use it in a emacs daemon loaded at login by a service, I would like to replace the scratch buffer mode to ocaml but (tuareg-mode) cause that error and service can't start when there's an error.

**Comment by diml** [comment]
The tuareg-mode itself doesn't know about utop. Are you sure you don't have something like this in your ~/.emacs:

```scheme
(add-hook 'tuareg-mode-hook 'utop-setup-ocaml-buffer)
```

**Comment by nscott32** [comment]
Yes I am sure, the only line where utop appear is (use-package utop :ensure t).
Also what I do since earlier is start (tuareg-mode) manually from the scratch buffer and then utop error just appears.

**Comment by nscott32** [comment]
You were right, there's a binding to that function in my use-package :config for tuareg, it was copied from the web and I didn't know what was really happening...
It is  those two lines : 
  (autoload 'utop-setup-ocaml-buffer "utop" "Toplevel for OCaml" t)
  (add-hook 'tuareg-mode-hook 'utop-setup-ocaml-buffer)
 
So I tried to replace it bit utop-minor mode in both, but it leads me to that error : 
(void-function tuareg-imenu-set-imenu)
  tuareg-imenu-set-imenu()
  run-hooks(change-major-mode-after-body-hook prog-mode-hook tuareg-load-hook tuareg-mode-hook)
  apply(run-hooks (change-major-mode-after-body-hook prog-mode-hook tuareg-load-hook tuareg-mode-hook))

**Comment by diml** [comment]
The only thing menu-related in utop.el is this code:

```elisp
(easy-menu-define
  utop-menu utop-mode-map
  "utop menu."
  '("utop"
    ["Start OCaml" utop t]
    ["Interrupt OCaml" utop-interrupt :active (utop-is-running)]
    ["Kill OCaml" utop-kill :active (utop-is-running)]
    ["Exit utop gracefully" utop-exit :active (utop-is-running)]
    ["Evaluate Phrase" utop-eval-input-auto-end :active (and (utop-is-running) (eq utop-state 'edit))]
    "---"
    ["Customize utop" (customize-group 'utop) t]
    "---"
    ["About" utop-about t]
    ["Help" utop-help t]))
```

You could try to comment it to see if it makes the problem go away. Just to be sure, if you remove `utop-minor-mode` entirely from your config do you get an error?

**Comment by nscott32** [comment]
Now it works !
There was also this line in the use-package :config 
  (add-hook 'tuareg-mode-hook 'tuareg-imenu-set-imenu)
And when removed with all the utop lines removed it works !
I have copied this from wikiemacs, I often have configuration that doesn't works fo me when I copy from it...
Thank you for your promptness, I am now happy to run tuareg-mode at startup !
