### ISSUE TITLE
Program hangs on utop specifically.

### ISSUE THREAD

**Issue by pveber** [diml/utop#154]
I have a program that hangs when run with `utop`, but runs fine on the `ocaml` interpreter, as well as in compiled mode. The problem has been reproduced on Linux and MacOSX architectures; it occurs inside a code that runs shell commands concurrently, but not exactly at the same place at each execution. I have not yet tried to isolate a minimal code (not easy, but doable I hope). Before taking on this road, I just wanted to ask if this (rather vague) description could ring someone a bell. If not I'll start minimizing the code. Thanks for any hint!

**Comment by pveber** [comment]
So I could produce a (remarkably) small program to reproduce the problem. The following program hangs:
```ocaml
#require "shell";;
#require "lwt.unix";;

open Lwt

let f () = Lwt_process.exec ("", [| "ls" |]) >|= ignore

let _ = Lwt_main.run (f ())
```
while this one doesn't:
```ocaml
#require "lwt.unix";;

open Lwt

let f () = Lwt_process.exec ("", [| "ls" |]) >|= ignore

let _ = Lwt_main.run (f ())
```
`shell` is a package from the `ocamlnet` library. I tried to have a look and I may have found the culprit: in the module `Shell_uq` of `shell`, we can read the following initialization:
```ocaml
let () =
  if not is_win32 then
    Netsys_posix.register_subprocess_handler()
    (* Install the SIGCHLD handler *)
```
Is there a way this could interfere with utop?

**Comment by diml** [comment]
Ah, it's not really utop but rather Lwt then. Lwt also install a SIGCHLD handler. Unfortunately there is no good solution for this; we would need some kind of common signal manager to make this work

**Comment by pveber** [comment]
Well, that all makes sense. Worst thing is that I was not even using `shell` anymore, which means the bug wouldn't show up in compiled mode. Ok so I think this issue is enough to document the fact that `shell` from ocamlnet is not compatible with `lwt` and may cause a program to hang. Thanks for the feedback!
