### ISSUE TITLE
utop outputs unprintable characters with invalid \y escapes

### ISSUE THREAD

**Issue by dsheets** [diml/utop#155]
This may be NOTABUG but I though the behavior was surprising so I am reporting it here:

```
# String.escaped "\247";;
- : bytes = "\yf7"
```

But `"\yf7"` is not a valid OCaml escape sequence. Utop (or lambdaterm?) does this because the output of `String.escaped "\247"` is the byte string with byte 247 unescaped but this is unprintable so utop replaces it with `\yf7` when printing. Maybe this is the right behavior so you know that it's utop doing the escaping? I think the escaping can be distinguished between `"\\247"` and `"\247"`, though.

I am using utop 1.18.1.

**Comment by diml** [comment]
Utop uses this format for invalid UTF8 in the output of the OCaml value printer. Utop has to do this as lambda-term accepts only valid UTF8 encoded strings and recode them to the terminal encoding.

I though this should normally never happen, but since up to 4.02.3 `String.escaped` uses the locale-dependent `isprint` function, depending on your locale settings it might decide that `\247` is printable and not escape it.

Maybe a better choice would be to just fallback to latin1 for invalid UTF8

**Comment by dsheets** [comment]
Thanks for the explanation.

I don't know what you mean by "fallback to latin1".

What about just outputting `"\247"` instead of `"\yf7"`?

**Comment by diml** [comment]
I meant replacing `\247` by `\195\183` (it's UTF-8 encoding). Basically anything that is not a valid UTF-8 sequence is interpreted as latin1 and recoded to valid UTF-8.
I don't remember exactly why I didn't do that originally. It seems that the terminal does this already so it's probably fine. I'll change the code

> What about just outputting "\247" instead of "\yf7"?

that's fine if the character is inside an OCaml string, if it's somewhere else - for instance it could be printed by a custom printer installed with `#install_printer` - it might not make much sense

**Comment by dsheets** [comment]
Oh, I see. I hadn't thought about the non-string value case. Can you have the string case print the normal escape sequence and the other cases do the re-coding?

**Comment by diml** [comment]
I did the Latin-1 fallback. My terminal seems to do the right thing when I start utop with Latin-1 settings:

```
LANG=en_US utop
[...]
# LTerm_unix.system_encoding;;
- : bytes = "ISO-8859-1"
# String.escaped "\247";;
- : bytes = "÷"
```

> Can you have the string case print the normal escape sequence and the other cases do the re-coding?

utop just fixes up the output of `Toploop.print_out_blah` without parsing it, to special case the string case the best is to simply install a custom string printer. In 4.03, string escaping is already system independent. I'll accept a patch to do the same with ocaml < 4.03

Out of curiosity, what system are you using and what's the contents of your `LANG` environment variable? Even on my mac I get `LANG=en_US.UTF-8` by default. I though non-UTF8 didn't really exist anymore... (except on windows)

**Comment by dsheets** [comment]
I am using OS X 10.11.3 right now. `LANG` is `en_US.UTF-8`. I don't expect correct interpretation of bytes as text. Rather, I was doing processing of sexplib output which contained high bytes. See janestreet/sexplib#18.

**Comment by diml** [comment]
OK, I wrongly assumed `isprint` would return the same thing on Linux and OSX...
