### ISSUE TITLE
It seems like the Build constantly fails at installing conf-ncurses version1.

### ISSUE THREAD

**Issue by fourtytwo** [diml/utop#159]
So basically what the title says. I cannot install "apparently"  ncurses-dev It tells me to run:   opam depext  conf-ncurses.1. And  it tells me that it has been installed but it still does not work.

**Comment by diml** [comment]
I don't really understand, does the utop build fails? utop doesn't use ncurses

**Comment by samoht** [comment]
@fourtytwo Which distro are you using?

**Comment by fourtytwo** [comment]
Ubuntu Gnome

**Comment by fourtytwo** [comment]
So now i neeed oasis... which i tried to install however againt it fails with the message it needs ncurses

**Comment by OCamlPro-Henry** [comment]
@fourtytwo What's the error message do you get when running `opam install conf-ncurses` ?

**Comment by fourtytwo** [comment]
@OCamlPro-Henry 
The following actions will be performed:
  ∗  install conf-ncurses 1

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[ERROR] The compilation of conf-ncurses failed at "pkg-config ncurses".

#=== ERROR while installing conf-ncurses.1 ====================================#
# opam-version 1.2.2
# os           linux
# command      pkg-config ncurses
# path         /home/julian/.opam/4.02.1/build/conf-ncurses.1
# compiler     4.02.1
# exit-code    127
# env-file     /home/julian/.opam/4.02.1/build/conf-ncurses.1/conf-ncurses-8632-4438d8.env
# stdout-file  /home/julian/.opam/4.02.1/build/conf-ncurses.1/conf-ncurses-8632-4438d8.out
# stderr-file  /home/julian/.opam/4.02.1/build/conf-ncurses.1/conf-ncurses-8632-4438d8.err



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
The following actions failed
  ∗  install conf-ncurses 1
No changes have been performed

=-=- conf-ncurses.1 troobleshooting -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
=> This package relies on external (system) dependencies that may be missing.
   `opam depext conf-ncurses.1' may help you find the correct installation for
   your system.

**Comment by dsheets** [comment]
You probably lack `pkg-config` and `conf-ncurses` should be dependent on `conf-pkg-config`.

**Comment by fourtytwo** [comment]
@dsheets THank you that solved the problem... any explaination what pkg-config is/entails that it seemed to not work due to that?

**Comment by dsheets** [comment]
`pkg-config` queries metadata files for installed libraries and generates the needed compiler and linker arguments from them in order for programs to link against them. In this case, it is used simply as a query for the package installaion. This error is being addressed in ocaml/opam-repository metadata to ensure `pkg-config` exists for the external dependencies that use it.
