### ISSUE TITLE
Utop fails to install with Ocaml 4.03.0

### ISSUE THREAD

**Issue by twopisoft** [diml/utop#168]
Hello,

I just updated to Ocaml version 4.03.0. After the update, utop 1.19 stopped working so I reinstalled it. But now I am getting a compilation error. Error output is attached.

Thanks

[err.txt](https://github.com/diml/utop/files/251988/err.txt)

**Comment by diml** [comment]
Hi, I looked at the log and it's trying to install utop 1.19. The latest released version is utop 1.19.2 which has some fixes for 4.03, could you retry with 1.19.2?

**Comment by twopisoft** [comment]
Moving to 1.19.2 solves the problem. Thanks!.

**Comment by diml** [comment]
no problem
