### ISSUE TITLE
Pasting code with newline silences errors

### ISSUE THREAD

**Issue by chenglou** [diml/utop#175]
Repro: paste the following into utop, including the newline (aka the blue section should extend til the end of the code block.

```
asdasd;;

```

Copying the new line happens quite often when copying a snippet of code. Upon pasting, the newline is pasted and the whole thing evaluated (without a manual `enter`). Utop silently fails while correctly underlining `asdasd`. Expected error: `Error: Unbound value asdasd`.

cc @yunxing @jordan

**Comment by yunxing** [comment]
Is this happening on master? My utop (1.19.2) actually works as expected:

**Comment by diml** [comment]
There was a race condition in lambda-term, it's now fixed

**Comment by diml** [comment]
I did a minor release with the fix:

https://github.com/ocaml/opam-repository/pull/7203

**Comment by chenglou** [comment]
Thanks!
