### ISSUE TITLE
utop creating infinitely new completion lines in #require

### ISSUE THREAD

**Issue by fxfactorial** [diml/utop#178]
utop is making these completion lines every time I try to do a completion on packages, it will be hard to explain in words, easier shown in this gif: 

![utop_crazy_behavior](https://cloud.githubusercontent.com/assets/3036816/18592673/e1dbd15c-7bec-11e6-9170-aa4ba6aa8c99.gif)

this is on OS X, confirmed in both iterm2 and plain terminal.app

utop: 1.19.3
ocaml: 4.03.0

**Comment by hcarty** [comment]
This is related to https://github.com/OCamlPro/ocp-index/pull/96 and https://github.com/OCamlPro/ocp-index/issues/97

It would be nice if utop could more cleanly capture and report the error.

**Comment by fxfactorial** [comment]
@hcarty nice, thanks, will close then

**Comment by hcarty** [comment]
@fxfactorial You're welcome!  I the fix in that PR came from seeing this exact issue on my system.
