### ISSUE TITLE
file completion for `#use` but not for `#mod_use`

### ISSUE THREAD

**Issue by vogler** [diml/utop#191]
I noticed that `#use` offers completion for files but `#mod_use` doesn't.

[version 1.19.3, compiled for OCaml version 4.03.0]

**Comment by diml** [comment]
It should work in the development version, but it's not yet released

**Comment by rgrinberg** [comment]
@diml could you  make a release with this improvement if possible?

**Comment by diml** [comment]
@rgrinberg just need to finish the jbuilder branch and I'll do a new release :)

**Comment by diml** [comment]
Implemented by #181
