### ISSUE TITLE
previous values

### ISSUE THREAD

**Issue by nilsbecker** [diml/utop#193]
For interactive work it would be helpful to have quick access to previous values. such as `ans` in Matlab, `_` in ipython, or `%` or `Out[n]` in Mathematica. I.e. either only the last evaluated value or, better, all previous values would be bound to an obvious identifier by default. It might become a memory problem, but I would think this would be rare; if this is a concern one could introduce the option to disable cumulative storage.

**Comment by diml** [comment]
Indeed, this is similar to #161

**Comment by nilsbecker** [comment]
yes - i didn't see that one. it's basically the same.

**Comment by diml** [comment]
Implemented by #200
