### ISSUE TITLE
utop-eval-buffer is broken in tuareg mode in emacs

### ISSUE THREAD

**Issue by chetnashah** [diml/utop#195]
Using M-x utop-eval-buffer for a .ml file, following error occurs.
```
utop-compat-skip-blank-and-comments: Symbol's function definition is void: tuareg-skip-blank-and-comments
```
tuareg code has probably renamed this variable to one with two dashes(tuareg--skip-blank-and-comments).

**Comment by diml** [comment]
Thanks for the report, the name change was reverted upstream
