### ISSUE TITLE
Define meaning of utop's emacs hooks

### ISSUE THREAD

**Issue by arichiardi** [diml/utop#201]
Hello folks/maintainer,

I have a compatibility layer to `utop` (actually `rtop`) in Reason and I am basically defining:

```
 ;;; utop.el
  (setq utop-discover-phrase 'reason-discover-phrase-debug)
  (setq utop-skip-blank-and-comments 'reason-skip-blank-and-comments)
  (setq utop-skip-to-end-of-phrase 'reason-find-phrase-end)
```

The problem is that I cannot understand clearly the semantic of `utop-skip-to-end-of-phrase`. I see [here](https://github.com/diml/utop/blob/master/src/top/utop.el#L854) that it is called to set a new `end` of the phrase, but if the triple returned by `utop-discover-phrase` is already returning the end position as "point after the semicolon", then why do we need to skip again?
The result of the above in my case basically is that two phrases are evaluated, unless I never skip anything in my `utop-skip-to-end-of-phrase`).

Maybe I am missing something here :smile: 

Thanks for reading and I hope the issue description is understandable enough.

**Comment by diml** [comment]
I understand the description, but TBH I wrote this code a long time ago and I can't remember all the details! These functions are basically aliases for the corresponding tuareg functions. `tuareg-skip-to-end-of-phrase` doesn't seem documented, maybe you could ask on the tuareg project?

**Comment by arichiardi** [comment]
Yes I went through tuareg's code but I think they use that for a different purpose (indentation). In fact, it goes backwards after a semicolon looking for a word (any).
This is why it works for them, they discover the end then they go back and rediscover the same end.
Kind of redundant and I believe that the call does not belong in `utop-eval'. I am willing to send a PR to take it away.

You can see what I use at the moment [here](https://github.com/arichiardi/reason/commit/2e013216e6383f3416c94ef2c7df1e0f1068b605#diff-410eaacc78db8d8e07ac7d7c5e06d5e0R1301).

**Comment by arichiardi** [comment]
Moreover, the function is used only in there, one place, meaning that it can be safely removed.

**Comment by diml** [comment]
I see, I agree that it doesn't belong in `utop-eval`. Looking at this more in details, I remember where this comes from. The code in `utop-eval` is similar to the code in `tuareg-eval-region`. So the call to `utop-skip-to-end-of-phrase` should probably be moved to `utop-eval-region`.

**Comment by arichiardi** [comment]
Ok i'll PR then and try things out, thanks for this btw, as Clojure dev I need a functioning repl (in Emacs!) 😀

**Comment by arichiardi** [comment]
On another note​ would you be open to add `reason-mode` in the supported ones, once the patch is in? I kind of don't like the dynamic load I am doing in there now...

**Comment by diml** [comment]
sure, no problem

**Comment by arichiardi** [comment]
I see that `tuareg-eval-region` [does not include](https://github.com/ocaml/tuareg/blob/master/tuareg.el#L3070) that anymore. Ready for getting rid of it :smile:?

**Comment by arichiardi** [comment]
It is used in `tuareg-discover-phrase` directly and in "previous-phrase".

**Comment by diml** [comment]
Oh, indeed. I was looking at the version I have installed on my box, which is older. Happy to get rid of it! Looks like we don't need `skip-blank-and-comments` either

**Comment by arichiardi** [comment]
Ah you're right because `discover-phrase` should already do the whole job for you.

**Comment by arichiardi** [comment]
Uhm, I think I found a use-case, when `utop-skip-after-eval-phrase` is true, we need to  found the next phrase using those `skip-blank-and-comments` in order to get to the beginning of the next phrase. Or I could create a `utop-skip-to-phrase-beginning` that client code needs to pass in.

**Comment by arichiardi** [comment]
To better define the behavior, all the `discover-phrase` go backwards in finding the beginning of the sentence, so after evaluation we cannot just call it again or we will eval the same phrase.
We need something the skips forward to the beginning of the next phrase, that is why `utop-skip-to-phrase-beginning` felt appropriate. Tuareg [has it already](https://github.com/ocaml/tuareg/blob/master/tuareg_indent.el#L1947).

**Comment by arichiardi** [comment]
OCaml moves [forward already](https://github.com/ocaml/ocaml/blob/70d880a41a82aae1ebd428fd38100e8467f8535a/emacs/caml.el#L976) and might not need it (in which case `identity` would do).
