### ISSUE TITLE
Async.Std warning shows up in toplevel

### ISSUE THREAD

**Issue by yminsky** [diml/utop#205]
I found this while updating Async for Real World OCaml. This appears in utop and in the ordinary toplevel as well. Any idea how?

```
utop # open Async;;
utop # let c = Reader.file_contents "test.txt";;
val c : string Deferred.t = <abstr>
utop # c;;
Characters 0-1:
Warning 3: deprecated: module Async.Std
[since 2017-02] use Async. The Std sub-module is no longer needed
- : string = ""
```

And here, I think, is the bug:

https://github.com/diml/utop/search?utf8=%E2%9C%93&q=Async.Std&type=

**Comment by let-def** [comment]
(I reported the issue happening in the ordinary toplevel too, but mine was patched to begin with, so my report was erroneous).
I replaced `Async.Std` by `Async` in `ocaml-topexpect`, the problem is gone.

**Comment by yminsky** [comment]
The problem does happen in utop, though, so I think this bug is legit.

**Comment by diml** [comment]
Yh, in utop i'll need to change the name and add a fallback to the old one, otherwise it's only going to work with async v0.9.0 which is not yet released

**Comment by yminsky** [comment]
Fwiw, Async.Deferred was probably already in the namespace, so it might
work to just use that everywhere...

**Comment by diml** [comment]
Indeed, this simplifies things
