### ISSUE TITLE
Async.Std.Deferred.t not automatically resolving

### ISSUE THREAD

**Issue by Rageoholic** [diml/utop#219]
So according to Real World OCaml utop should display this behavior
```
utop[9]> let three = return 3;;
val three : int Deferred.t = <abstr>
utop[10]> three;;
- : int = 3
```
but instead I get
```
utop[9]> let three = return 3;;
val three : int Deferred.t = <abstr>
utop[10]> three;;
- : int Deferred.t = <abstr>
```
Additionally, the scheduler isn't running in the background and so three never gets fulfilled? How can I force utop to do the behavior real world ocaml says it should be having.

**Comment by agarwal** [comment]
I think you need utop > 2.0.0. See #137.

**Comment by Rageoholic** [comment]
I have 2.0.1 though

**Comment by agarwal** [comment]
Hmm, not sure then. I can't reproduce:

```
$ utop -version
The universal toplevel for OCaml, version 2.0.1, compiled for OCaml version 4.03.0
$ utop -init ""
utop # #require "async";;
utop # open Core;;
utop # open Async;;
utop # let three = return 3;;
val three : int Deferred.t = <abstr>
utop # three;;
- : int = 3
```

**Comment by Rageoholic** [comment]
Well here's my .ocamlinit if it helps at all

**Comment by Rageoholic** [comment]
OK I rebuilt the world from scratch and now everything works as intended. I have no idea why but I suspect it has to do with the version of ocaml ubuntu ships out of the box.

**Comment by agarwal** [comment]
Glad to hear it is working. You can probably close this issue then.
