### ISSUE TITLE
failed to install `utop.1.19.3`: cppo_ocamlbuild not found

### ISSUE THREAD

**Issue by gitoleg** [diml/utop#220]
failed to install `utop.1.19.3` 
```
#=== ERROR while installing utop.1.19.3 =======================================#
# opam-version 1.2.2
# os           linux
# command      make
# path         /home/oleg/.opam/fresh_4.03.0/build/utop.1.19.3
# compiler     4.03.0
# exit-code    2
# env-file     /home/oleg/.opam/fresh_4.03.0/build/utop.1.19.3/utop-22008-e4db2f.env
# stdout-file  /home/oleg/.opam/fresh_4.03.0/build/utop.1.19.3/utop-22008-e4db2f.out
# stderr-file  /home/oleg/.opam/fresh_4.03.0/build/utop.1.19.3/utop-22008-e4db2f.err
### stdout ###
# [...]
# pkg_lambda_term: ..................................... /home/oleg/.opam/fresh_4.03.0/lib/lambda-term
# ocamldoc: ............................................ /home/oleg/.opam/fresh_4.03.0/bin/ocamldoc
# gzip: ................................................ /bin/gzip
# 
# ./setup.exe -build 
# ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package cppo_ocamlbuild myocamlbuild.ml /home/oleg/.opam/fresh_4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# + ocamlfind ocamlopt -package unix -package ocamlbuild -linkpkg -package cppo_ocamlbuild myocamlbuild.ml /home/oleg/.opam/fresh_4.03.0/lib/ocamlbuild/ocamlbuild.cmx -o myocamlbuild
# ocamlfind: Package `cppo_ocamlbuild' not found
```
I think the reson is in last `cppo.1.6.0`, since with previous `cppo.1.5.0` utop works fine.
https://github.com/ocaml/opam-repository/pull/10047

As far as  I understand (and maybe I'm wrong)  all we need is either constraint `cppo` version in opam or add a dependency from `cppo_ocamlbuild`.

**Comment by rgrinberg** [comment]
Any reason why you can't just use the latest version of utop (which doesn't ocamlbuild at all)? You can also just fix the opam file in the opam-repository directly if you'd like.

**Comment by gitoleg** [comment]
we have to use this version because latest doesn't work for us, we have a runtime error like `Error: Reference to undefined global `Longident'`. (as it was discussed https://github.com/diml/utop/issues/213 )
So will do PR to opam-repository ) ￼ ￼

**Comment by gitoleg** [comment]
so PR to opam was merged:
https://github.com/ocaml/opam-repository/pull/10582
Issue may be closed
