### ISSUE TITLE
Release compatible with ocaml 4.07

### ISSUE THREAD

**Issue by bschommer** [diml/utop#244]
It seems that trunk at least compiles with 4.07, is there still anything missing?

**Comment by pmetzger** [comment]
Indeed, is there anything in the way of such a release? 4.07 is not nearly so useful without utop.

**Comment by shinzui** [comment]
This seems like an oversight in the release process. utop should be part of the core packages that should always work with new versions of OCaml.

**Comment by pmetzger** [comment]
@shinzui there's no notion in the current release process of "core packages" that are checked for compatibility, but I think a volunteer group that made sure that a particular set of packages was ready for 4.08 before it was released would be welcome. You might want to bring the topic up on discuss.ocaml.org

**Comment by rgrinberg** [comment]
Seems like it's just an oversight. I will make a release promptly

**Comment by bschommer** [comment]
Works fine now, thanks for the fast fix.
